### ISSUE TITLE
Module POD is inconsistent

### ISSUE THREAD

**Issue by robrwo** [scottchiefbaker/perl-Random-Simple#1]
Generally, Perl modules have other `=head1` sections
- a SYNOPSIS section instead of "Usage"
- a DESCRIPTION section 
- an EXPORTS section (instead of "Functions")

**Comment by scottchiefbaker** [comment]
I just landed an update in 7572832. Give that a preview and let me know?

I used `Math::Random::PCG32` and `Math::Random::MT` as a template
