### ISSUE TITLE
Metadata needs to be fixed

### ISSUE THREAD

**Issue by robrwo** [scottchiefbaker/perl-Random-Simple#2]
MetaCPAN points to RT https://rt.cpan.org/Public/Dist/Display.html?Name=Random-Simple instead of GitHub issues. Either fix the metadata to point to GitHub issues here, or disable the Issues in your GitRepo.

You should also mention something in the POD as to where to report bugs. Many modules have a BUGS or SUPPORT section.

**Comment by scottchiefbaker** [comment]
This sounds like an easy fix. How/where do I fix the metadata? I'll add a section to the pod right now.

**Comment by robrwo** [comment]
> This sounds like an easy fix. How/where do I fix the metadata?

In the `Makefile.PL`. Under resources you'd add
```perl
                      bugtracker => {
                                     "web" => "https://github.com/scottchiefbaker/perl-Random-Simple/issues"
                                    }
```

**Comment by scottchiefbaker** [comment]
This should be completed in 40141b7. Thanks for the info, I'm not sure familiar with the `Makefile.PL` stuff yet.
